name: CI
on: [push, pull_request]
jobs:
  realese:
    name: Criação de realese
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' && github.ref == 'refs/heads/dev' && startsWith(github.event.head_commit.message, '[UP]')"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Package Version
        id: info
        run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"
      - name: Compactar os arquivos
        uses: thedoctor0/zip-release@master
        with:
          filename: 'lavalink-nodejs.zip'
          exclusions: '*.git* *.eslintrc.json *package-lock.json'
      - name: Enviar para a realese
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./lavalink-nodejs.zip
          tag_name: ${{ steps.info.outputs.version }}
          name: Lavalink Update v${{ steps.info.outputs.version }}
          draft: true
          prerelease: false
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  artifact:
    name: Criação de Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compactar os arquivos
        uses: thedoctor0/zip-release@master
        with:
          filename: 'lavalink-nodejs.zip'
          exclusions: '*.git* *.eslintrc.json *package-lock.json *yarn.lock'
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: 'lavalink-nodejs.zip'
